---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: db
spec:
  members: 1
  type: ReplicaSet
  version: "6.0.5"
  security:
    authentication:
      modes: [ "SCRAM" ]
  users:
    - name: db-admin
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: db-admin-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  statefulSet:
    spec:
      template:
        spec:
          containers:
            - name: mongod
              resources:
                requests:
                  cpu: "250m"
                  memory: 0.5Gi
            - name: mongodb-agent
              resources:
                requests:
                  cpu: "250m"
                  memory: 0.5Gi