---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: web
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: web

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - image: us-east1-docker.pkg.dev/birding-by-the-numbers/web/web:test7
          name: web
          resources:
            requests:
              cpu: "250m"
              memory: 0.5Gi
          env:
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: google-oauth
                  key: clientId
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: google-oauth
                  key: clientSecret
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: next-auth
                  key: secret
            - name: NEXTAUTH_URL
              value: https://birdingbythenumbers.com
            - name: DB_URI
              valueFrom:
                secretKeyRef:
                  name: db-admin-admin
                  key: connectionString.standardSrv
            - name: MQ_HOST
              valueFrom:
                secretKeyRef:
                  name: ebird-mq-default-user
                  key: host
            - name: MQ_PORT
              valueFrom:
                secretKeyRef:
                  name: ebird-mq-default-user
                  key: port
            - name: MQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ebird-mq-default-user
                  key: username
            - name: MQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ebird-mq-default-user
                  key: password
